default['jenkins']['repo']['url'] = "http://pkg.jenkins-ci.org/redhat/jenkins.repo"
default['jenkins']['repo']['gpgkey'] = "http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key"
default['jenkins']['user'] = "jenkins"
default['jenkins']['port']['http'] = "8080"
default['jenkins']['port']['ajp'] = "8009"
